-- MySQL Script generated by MySQL Workbench
-- Sun Nov  8 11:44:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UIPRCMSDDL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UIPRCMSDDL` ;

-- -----------------------------------------------------
-- Schema UIPRCMSDDL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UIPRCMSDDL` DEFAULT CHARACTER SET utf8 ;
USE `UIPRCMSDDL` ;

-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` MEDIUMBLOB NULL,
  `type` VARCHAR(45) NULL,
  `size` FLOAT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `type_id` INT NOT NULL,
  `image_id` INT NULL,
  `published_date` DATE NOT NULL,
  `year_only` TINYINT NULL DEFAULT 0,
  `description` MEDIUMTEXT NOT NULL,
  `meta` LONGTEXT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_item_type1_idx` (`type_id` ASC),
  INDEX `fk_item_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_item_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `UIPRCMSDDL`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `UIPRCMSDDL`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `author_name_UNIQUE` (`author_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `subject`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `subject_UNIQUE` (`subject` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`author_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`author_has_item` (
  `item_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`item_id`, `author_id`),
  INDEX `fk_Authors_has_Items_Items1_idx` (`item_id` ASC),
  INDEX `fk_Authors_has_Items_Authors_idx` (`author_id` ASC),
  CONSTRAINT `fk_Authors_has_Items_Authors`
    FOREIGN KEY (`author_id`)
    REFERENCES `UIPRCMSDDL`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authors_has_Items_Items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `UIPRCMSDDL`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NULL,
  `content` LONGBLOB NULL,
  `type` VARCHAR(255) NULL,
  `size` FLOAT NULL,
  `path` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`item_has_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`item_has_subject` (
  `item_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`item_id`, `subject_id`),
  INDEX `fk_item_has_subject_subject1_idx` (`subject_id` ASC),
  INDEX `fk_item_has_subject_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_item_has_subject_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `UIPRCMSDDL`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_subject_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `UIPRCMSDDL`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`file_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`file_has_item` (
  `file_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`file_id`, `item_id`),
  INDEX `fk_file_has_item_item1_idx` (`item_id` ASC),
  INDEX `fk_file_has_item_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_file_has_item_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `UIPRCMSDDL`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `UIPRCMSDDL`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UIPRCMSDDL`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UIPRCMSDDL`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Dumping data for table `type`
-- -----------------------------------------------------

INSERT INTO `type` (`id`, `type`) VALUES
(3, 'Arte'),
(1, 'Documento'),
(6, 'Folleto'),
(4, 'Foto'),
(2, 'Libro'),
(5, 'Periódico'),
(7, 'Revista');